language: julia
os:
- linux
julia:
- 1.0
notifications:
  email: false
git:
  depth: 99999999
cache:
  timeout: 1000
  directories:
  - downloads
env:
  global:
  - BINARYBUILDER_DOWNLOADS_CACHE=downloads
  - BINARYBUILDER_AUTOMATIC_APPLE=true
sudo: required
before_script:
- cd ..
- julia -e 'using Pkg; Pkg.add(PackageSpec(name="BinaryProvider"))'
- julia -e 'using Pkg; Pkg.add(PackageSpec(name="BinaryBuilder"))'
script:
- julia --color=yes FastJetWrapBuilder/.ci/build_tarballs.jl --verbose
- ls -l products/*
deploy:
  provider: releases
  api_key:
    secure: guslhgjufRa8oPLmAS2ToFXFlGRVdsu1SrKDnqJLwXu/eLG9TZabNYykF/k/VD47bHo5hI/3ViTjlEQj1uWfnvdw7iBf9jBO+n/j77R/ME6twC3OiBveH40SR1QXB4yaJ+Hw6rFMCE/QrXaEDZFrDtQs7d4ltRuthJ2fZJWIlVkNYq85OJ06N9ecuOx8sW/vBHICyDcq4qxk14uaoIH6Wx6UI3fFgc9Q9yfKVy7LeBYwxnfwpvMCqCWQ34XJZmx4tzNtdQCdf3Vr3PUJyhOCHp5MIkQK5KMhB8li8NiFxyAjdvAkC/b4kKXQLxj/fjShpXquHUOWl3FpueVnL32HjuPUYbXfdsDa+lZVY+ASdV4kh8oZwlxfzbz+U4Ek2Z9CePi6CEumLZgyg1HAF7N+xHAsfdpz24s+LFGfsjI0jHBN34HgVNoPpbAeHX28GkSE5soNhP8f0LEAVOLHWTD4WzR1piz7JDpV2ctg2zjGTfQyQvRahme1iItEVKcGMWJoYKBGVVJmN+zfzDrSbxkkdgqOUjKkrH6J2iHJjA7bpeW2OdUo5PQ6xjjbJzrEUsW31pEGrS9VcondlrVPTaNxV4OWRjzpRboYvzJMa5PRsXscFLT368u39r/pQqGa++y7TXXtNy95zpMYQnzNI86+ubnbupu7e2xbalPt/475BS4=
  file_glob: true
  file: products/*
  skip_cleanup: true
  on:
    repo: jstrube/FastJetWrapBuilder
    tags: true
